### ISSUE TITLE
配置报错

### ISSUE THREAD

**Issue by 841023856** [QMUI/QMUI_iOS#1595]
**Bug 表现**
问题的具体描述
运行就 报错
**截图**
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '如果你看到这条提示，建议到 GitHub 上提 issue，让我们联系你查看项目的配置表使用情况，否则请注释掉这一行。'
*** First throw call stack:
(0x1a1f0c7cc 0x19f1df2e4 0x1a12dc8d8 0x1067d67b0 0x106906758 0x10767671c 0x1076782a0 0x106905f34 0x19f1cc820 0x1c78a2d10 0x1c78db908 0x1c78db8b4 0x1c78db8b4 0x1c78dd2c8 0x1c78a8c00 0x1c7898280 0x1c78acd10 0x1c78d19f8 0x1c78cacb0)
libc++abi: terminating due to uncaught exception of type NSException

**如何重现**
1. 必显

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [模拟器、iPhone]
 - iOS 版本: [iOS 18.1]
 - Xcode 版本: [Xcode 16.1]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
<img width="1224" alt="image" src="https://github.com/user-attachments/assets/d9063172-8b3a-4fc4-b74d-31318f5c70f2">

**Comment by chglog** [comment]
我也遇到了

**Comment by chglog** [comment]
*** Assertion failure in -[QMUIConfiguration applyInitialTemplate], QMUIConfiguration.m:101
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '如果你看到这条提示，建议到 GitHub 上提 issue，让我们联系你查看项目的配置表使用情况，否则请注释掉这一行。'
*** First throw call stack:
(0x1995287cc 0x1967fb2e4 0x1988f88d8 0x1056cfbd4 0x1057db648 0x104a0271c 0x104a042a0 0x1057dae64 0x1967e8820 0x1beebed10 0x1beef7908 0x1beef78b4 0x1beef78b4 0x1beef92c8 0x1beec4c00 0x1beeb4280 0x1beec8d10 0x1beeed9f8 0x1beee6cb0)
libc++abi: terminating due to uncaught exception of type NSException

iOS 版本: [iOS 18.1]
Xcode 版本: [Xcode 16.1]
QMUI 版本: [4.x.x]
iPhoneXS max

**Comment by 841023856** [comment]
暂时的解决办法是，手动注释掉这一行代码，就不会闪退了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月11日(星期一) 下午4:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/QMUI_iOS] 配置报错 (Issue #1595)














 
*** Assertion failure in -[QMUIConfiguration applyInitialTemplate], QMUIConfiguration.m:101
 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '如果你看到这条提示，建议到 GitHub 上提 issue，让我们联系你查看项目的配置表使用情况，否则请注释掉这一行。'
 *** First throw call stack:
 (0x1995287cc 0x1967fb2e4 0x1988f88d8 0x1056cfbd4 0x1057db648 0x104a0271c 0x104a042a0 0x1057dae64 0x1967e8820 0x1beebed10 0x1beef7908 0x1beef78b4 0x1beef78b4 0x1beef92c8 0x1beec4c00 0x1beeb4280 0x1beec8d10 0x1beeed9f8 0x1beee6cb0)
 libc++abi: terminating due to uncaught exception of type NSException
 
iOS 版本: [iOS 18.1]
 Xcode 版本: [Xcode 16.1]
 QMUI 版本: [4.x.x]
 iPhoneXS max
