### ISSUE TITLE
QMUICommonViewController titleView should consider UINavigationBar appearance. 

### ISSUE THREAD

**Issue by caoer** [QMUI/QMUI_iOS#412]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`10.x`
- [x] QMUI iOS 版本：`2.8.1`

### 请描述具体问题

I assume that the QMUICommonViewController is a drop-in replacement for UIViewController to serve as the BaseViewController for our project, but it seems that is not true for now. **The problem is that when we set the UINavigationBar's appearance, it doesn't take effects for ViewController that is a sub-class of QMUICommonViewController**

After looking into the detail, we found out that QMUICommonViewController's titleView doesn't honer UINavigatinBar appearance. The style of the titleView is using `NavBarTitleFont`, which is nil by default. IMHO, if we are not set such variable in `QMUIConfiguration`, we should return the systemwide default value for it's consumers.

**Comment by MoLice** [comment]
The intent of most QMUI classes was to provide drop-in replacements for their counterparts. In essence, QMUI classes are supersets, providing features in addition to those shipped with the system. Seen from this angle, `QMUICommonViewController` and `QMUINavigationTitleView` not responding to `[UINavigationBar appearance].titleTextAttributes` is inconsistent with our design, and we'll work to get it fixed in the coming releases.

Furthermore, `QMUIConfigurationTemplate` can be seen as an equivalent of `UIAppearance`, but with a higher priority. If both `NavBarTitleFont` and `[UINavigationBar appearance].titleTextAttributes` are set, the former will take precedence. If `NavBarTitleFont` is not present, the latter will take effect.

**Comment by MoLice** [comment]
Fixed in [2.9.0](https://github.com/QMUI/QMUI_iOS/releases/tag/2.9.0).
